adb devices
adb shell pm disable-user android.autoinstalls.config.samsung
adb shell pm disable-user com.android.apps.tag
adb shell pm disable-user com.android.bips
adb shell pm disable-user com.android.bluetoothmidiservice
adb shell pm disable-user com.android.bookmarkprovider
adb shell pm disable-user com.android.carrierdefaultapp
adb shell pm disable-user com.android.chrome
adb shell pm disable-user com.android.dreams.basic
adb shell pm disable-user com.android.dreams.phototable
adb shell pm disable-user com.android.egg
adb shell pm disable-user com.android.hotwordenrollment.okgoogle
adb shell pm disable-user com.android.hotwordenrollment.xgoogle
adb shell pm disable-user com.android.internal.systemui.onehanded.gestural
adb shell pm disable-user com.android.managedprovisioning
adb shell pm disable-user com.android.providers.partnerbookmarks
adb shell pm disable-user com.android.sharedstoragebackup
adb shell pm disable-user com.android.stk
adb shell pm disable-user com.android.stk2
adb shell pm disable-user com.android.traceur
adb shell pm disable-user com.facebook.appmanager
adb shell pm disable-user com.facebook.services
adb shell pm disable-user com.facebook.system
adb shell pm disable-user com.google.android.apps.accessibility.voiceaccess
adb shell pm disable-user com.google.android.apps.carrier.carrierwifi
adb shell pm disable-user com.google.android.apps.messaging
adb shell pm disable-user com.google.android.apps.restore
adb shell pm disable-user com.google.android.apps.tachyon
adb shell pm disable-user com.google.android.apps.turbo
adb shell pm disable-user com.google.android.as
adb shell pm disable-user com.google.android.as.oss
adb shell pm disable-user com.google.android.cellbroadcastreceiver
adb shell pm disable-user com.google.android.feedback
adb shell pm disable-user com.google.android.gms.location.history
adb shell pm disable-user com.google.android.gms.supervision
adb shell pm disable-user com.google.android.onetimeinitializer
adb shell pm disable-user com.google.android.partnersetup
adb shell pm disable-user com.google.android.projection.gearhead
adb shell pm disable-user com.google.android.tts
adb shell pm disable-user com.google.audio.hearing.visualization.accessibility.scribe
adb shell pm disable-user com.hiya.star
adb shell pm disable-user com.knox.vpn.proxyhandler
adb shell pm disable-user com.microsoft.appmanager
adb shell pm disable-user com.microsoft.skydrive
adb shell pm disable-user com.samsung.android.aircommandmanager
adb shell pm disable-user com.samsung.android.allshare.service.mediashare
adb shell pm disable-user com.samsung.android.app.camera.sticker.facearavatar.preload
adb shell pm disable-user com.samsung.android.app.clipboardedge
adb shell pm disable-user com.samsung.android.app.cocktailbarservice
adb shell pm disable-user com.samsung.android.app.omcagent
adb shell pm disable-user com.samsung.android.app.readingglass
adb shell pm disable-user com.samsung.android.app.reminder
adb shell pm disable-user com.samsung.android.app.routines
adb shell pm disable-user com.samsung.android.app.settings.bixby
adb shell pm disable-user com.samsung.android.app.taskedge
adb shell pm disable-user com.samsung.android.app.watchmanagerstub
adb shell pm disable-user com.samsung.android.appseparation
adb shell pm disable-user com.samsung.android.ardrawing
adb shell pm disable-user com.samsung.android.aremoji
adb shell pm disable-user com.samsung.android.aremojieditor
adb shell pm disable-user com.samsung.android.authfw
adb shell pm disable-user com.samsung.android.aware.service
adb shell pm disable-user com.samsung.android.bbc.bbcagent
adb shell pm disable-user com.samsung.android.beaconmanager
adb shell pm disable-user com.samsung.android.bixby.agent
adb shell pm disable-user com.samsung.android.bixby.wakeup
adb shell pm disable-user com.samsung.android.bixbyvision.framework
adb shell pm disable-user com.samsung.android.cidmanager
adb shell pm disable-user com.samsung.android.cmfa.framework
adb shell pm disable-user com.samsung.android.da.daagent
adb shell pm disable-user com.samsung.android.dkey
adb shell pm disable-user com.samsung.android.easysetup
adb shell pm disable-user com.samsung.android.emergency
adb shell pm disable-user com.samsung.android.fast
adb shell pm disable-user com.samsung.android.fmm
adb shell pm disable-user com.samsung.android.forest
adb shell pm disable-user com.samsung.android.game.gamehome
adb shell pm disable-user com.samsung.android.game.gametools
adb shell pm disable-user com.samsung.android.game.gos
adb shell pm disable-user com.samsung.android.ipsgeofence
adb shell pm disable-user com.samsung.android.kidsinstaller
adb shell pm disable-user com.samsung.android.knox.analytics.uploader
adb shell pm disable-user com.samsung.android.knox.attestation
adb shell pm disable-user com.samsung.android.knox.containercore
adb shell pm disable-user com.samsung.android.knox.kpecore
adb shell pm disable-user com.samsung.android.knox.pushmanager
adb shell pm disable-user com.samsung.android.mcfserver
adb shell pm disable-user com.samsung.android.mdecservice
adb shell pm disable-user com.samsung.android.mdx
adb shell pm disable-user com.samsung.android.mdx.kit
adb shell pm disable-user com.samsung.android.net.wifi.wifiguider
adb shell pm disable-user com.samsung.android.peripheral.framework
adb shell pm disable-user com.samsung.android.rubin.app
adb shell pm disable-user com.samsung.android.samsungpass
adb shell pm disable-user com.samsung.android.samsungpassautofill
adb shell pm disable-user com.samsung.android.service.livedrawing
adb shell pm disable-user com.samsung.android.service.peoplestripe
adb shell pm disable-user com.samsung.android.service.stplatform
adb shell pm disable-user com.samsung.android.smartcallprovider
adb shell pm disable-user com.samsung.android.smartmirroring
adb shell pm disable-user com.samsung.android.smartsuggestions
adb shell pm disable-user com.samsung.android.smartswitchassistant
adb shell pm disable-user com.samsung.android.spayfw
adb shell pm disable-user com.samsung.android.stickercenter
adb shell pm disable-user com.samsung.android.visionintelligence
adb shell pm disable-user com.samsung.android.visualars
adb shell pm disable-user com.samsung.app.newtrim
adb shell pm disable-user com.samsung.cmfa.AuthTouch
adb shell pm disable-user com.samsung.faceservice
adb shell pm disable-user com.samsung.klmsagent
adb shell pm disable-user com.samsung.knox.securefolder
adb shell pm disable-user com.samsung.safetyinformation
adb shell pm disable-user com.samsung.ssu
adb shell pm disable-user com.samsung.storyservice
adb shell pm disable-user com.sec.android.app.billing
adb shell pm disable-user com.sec.android.app.chromecustomizations
adb shell pm disable-user com.sec.android.app.magnifier
adb shell pm disable-user com.sec.android.app.myfiles
adb shell pm disable-user com.sec.android.app.quicktool
adb shell pm disable-user com.sec.android.app.safetyassurance
adb shell pm disable-user com.sec.android.app.wlantest
adb shell pm disable-user com.sec.android.autodoodle.service
adb shell pm disable-user com.sec.android.easyMover.Agent
adb shell pm disable-user com.sec.android.mimage.avatarstickers
adb shell pm disable-user com.sec.android.widgetapp.easymodecontactswidget
adb shell pm disable-user com.sec.android.widgetapp.webmanual
adb shell pm disable-user com.sec.epdgtestapp
adb shell pm disable-user com.sec.location.nsflp2
adb shell pm disable-user com.sec.mhs.smarttethering
adb shell pm disable-user com.sec.spp.push
adb shell pm disable-user com.wsomacp
adb shell pm disable-user de.axelspringer.yana.zeropage
adb shell pm disable-user com.instagram.android
adb shell pm disable-user com.google.android.apps.googleassistant
adb shell pm disable-user com.google.android.adservices.api
adb shell pm disable-user com.google.android.ondevicepersonalization.services
adb shell pm disable-user com.aura.oobe.samsung.gl
adb shell pm disable-user com.qualcomm.location
adb shell pm disable-user com.samsung.android.mobileservice
adb shell pm disable-user com.sec.android.daemonapp
adb shell pm disable-user com.samsung.android.app.parentalcare
adb shell pm disable-user com.samsung.android.rampart
adb shell pm disable-user com.samsung.android.sm.devicesecurity
adb shell pm disable-user com.samsung.android.mapsagent
adb shell pm disable-user com.samsung.android.samsungpositioning
adb shell pm disable-user com.google.android.printservice.recommendation
adb shell pm disable-user com.samsung.android.intellivoiceservice
adb shell pm disable-user com.samsung.android.scloud
adb shell pm disable-user com.samsung.android.scpm
adb shell pm disable-user com.samsung.android.smartface
adb shell pm disable-user com.sec.android.app.personalization
adb shell pm disable-user com.samsung.petservice